services:
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - app-net
  
  db:
    image: "postgres:alpine"
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: wordcount
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app-net
    depends_on:
      - redis
  
  worker:
    build: ./worker
    networks:
      - app-net
    depends_on:
      - redis
      - db  
  
  result-frontend:
    build: ./result-frontend
    ports:
      - "7000:5000"
    networks:
      - app-net
    depends_on:
      - db
  
networks:
    app-net:
      driver: bridge
  
volumes:
    postgres_data:  